### ISSUE TITLE
Extremely long stitched exon from short contig and reference - Possibly Solved

### ISSUE THREAD

**Issue by HeatherKates** [juliema/aTRAM#249] opened 2019-06-22 00:43 UTC
[test.zip](https://github.com/juliema/aTRAM/files/3316371/test.zip)
Hi Julie and Rafe,

I just identified this issue, but it's been there from the start with our data. For one out of our 100 target loci, the stitched exons are extremely long across all samples- a couple orders of magnitude longer than the contigs or reference. I've attached a test directory that contains an example of the input as well as output, but you'll likely need to rerun to view all the output printed by exonerate. I can't look over all of this output typically because this is done for so many loci and samples, but even now that I've tested with one sample and one locus, I don't see any red flags in the output and I'm not sure what's exonerate output and what's printed from exon_stitching.sh. This could be an exonerate issue. Whatever it is it seems to be just affecting this locus but it's a puzzle to me. Any ideas? Thank you.

**Comment by juliema** [comment] 2019-06-22 00:46
hey Heather,  Thanks for the data. Rafe has actually been working on completely revamping the exon stitching code and adding it into atram. we are going to tag a new release next week. I will test the new code with these files to see if the issue is still there.    Thanks for the heads upl

**Comment by juliema** [comment] 2019-06-22 00:47
just a quick note. I think Rafe found the issue that was causing some to be extremely long like this. but again I will test it.

**Comment by HeatherKates** [comment] 2019-06-22 00:47
Hi Julie,

Ok Thanks. That's exciting! For now I'll just exclude this locus from our analyses until the new release is available and it's figured out.

Heather Rose

**Comment by HeatherKates** [comment] 2019-06-22 00:54
> just a quick note. I think Rafe found the issue that was causing some to be extremely long like this. but again I will test it.

Ok that's good to know that it's not unprecedented

**Comment by juliema** [comment] 2019-06-27 19:43
Ok this test dataset has the same formatting issue as issue 255 so I cant test this quite yet. when 255 is solved we can check this one.

**Comment by juliema** [comment] 2019-07-12 21:27
heather I think this is resolved in the new version!  yay! I just reran your locus and the output is much shorter than the one you sent.

**Closed by juliema** 2019-07-12 21:27 UTC
Labels: Medium Priority

**Comment by HeatherKates** [comment] 2019-07-15 15:52
Great news, thank you Julie! I'll restitch those exons prior to the next round of assembly.

**Comment by juliema** [comment] 2019-07-15 22:02
sounds good the stitcher is now in atram we are working on a little write up but look at the -h menu with the stitcher. let us know if you have any questions.

OH we need to tag a new release on hipergator so you can use it.



On Mon, Jul 15, 2019 at 10:52 AM Heather Kates <notifications@github.com<mailto:notifications@github.com>> wrote:

Great news, thank you Julie! I'll restitch those exons prior to the next round of assembly.
